name: keywordtool-scraper
dependencies:
- certifi=2016.2.28=py27_0
- fontconfig=2.12.6=0
- freetype=2.8.1=0
- icu=58.2=0
- libiconv=1.15=0
- libpng=1.6.34=0
- libxml2=2.9.4=4
- libxslt=1.1.29=0
- lxml=3.8.0=py27_0
- openssl=1.0.2l=0
- phantomjs=2.1.1=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=36.4.0=py27_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - selenium==3.8.1
